//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEmarketingProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Products()
        {
            this.tbl_Images = new HashSet<tbl_Images>();
        }
    
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_price { get; set; }
        public string pro_description { get; set; }
        public Nullable<int> pro_fk_user { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
        public int pro_status { get; set; }
        public System.DateTime pro_add_date { get; set; }
    
        public virtual tbl_Categories tbl_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Images> tbl_Images { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
