//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEmarketingProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tbl_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Users()
        {
            this.tbl_Products = new HashSet<tbl_Products>();
        }
    
        public int u_id { get; set; }
        public string u_username { get; set; }
        public string u_email { get; set; }
        public string u_password { get; set; }
        public string u_gender { get; set; }
        public string u_phone { get; set; }
        public string u_country { get; set; }
        public string u_image { get; set; }

        public HttpPostedFileBase ImgFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Products> tbl_Products { get; set; }
    }
}
