//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEmarketingProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tbl_Admins
    {
        public int a_id { get; set; }
        public string a_username { get; set; }
        public string a_email { get; set; }
        public string a_password { get; set; }
        public string a_image { get; set; }

        public HttpPostedFileBase ImgFile { get; set; }
    }
}
